version: '3.8'

services:
  weather-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    restart: unless-stopped
